[[camel-k-eventing]]
== Camel-K Eventing
include::_attributes.adoc[]

At the end of this chapter you will be able to:

- How to use Knative Eventing Channels with Camel-K
- Using Knative CamelSource
- Connect Camel-K source to Sink


ifndef::workshop[]
[#camel-k-eve-prerequisite]
== Prerequisite

include::knative-tutorial:ROOT:partial$prereq-cli.adoc[]

endif::[]

[#deploy-camel-k-source]
=== Deploy Knative Eventing CamelSource

The `CamelSource` allows you use a Camel-K integration as part of the Knative Eventing architecture. Simply speaking, you can make the Camel-K integration act as a https://knative.dev/docs/eventing/sources/[Knative Event Source] and  send the Camel exchanges (OUT) through a Knative Event Sink.

To deploy CamelSource run the following command:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#deploy-camelsource]
[source,bash,subs="+quotes,+attributes,+macros"]
----
kubectl apply \
  -f "https://github.com/knative/eventing-contrib/releases/download/{camel-source-version}/camel.yaml"
----
copyToClipboard::deploy-camelsource[]
--
oc::
+
--
endif::[]
[NOTE]
======
Use the OperatorHub in OpenShift web console to deploy the Knative Camel operator that will install the Knative Eventing CamelSource
======
ifndef::workshop[]
--
endif::[]
====

Once you deploy, thee following new pod showing up the `knative-sources` namespace:

[source,bash,subs="+quotes,+attributes,+macros"]
----
NAME                         READY   STATUS    RESTARTS   AGE
camel-controller-manager-0   1/1     Running   0          12h
----

Plus, CamelSource is now part of the API for your Kubernetes cluster:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#camel-k-camelsource-api]
[source,bash,subs="+quotes,+attributes,+macros"]
----
kubectl api-resources --api-group=sources.eventing.knative.dev
----
copyToClipboard::camel-k-camelsource-api[]
--
oc::
+
--
endif::[]
[#oc-camel-k-camelsource-api]
[source,bash,subs="+quotes,+attributes,+macros"]
----
kubectl api-resources --api-group=sources.eventing.knative.dev
----
copyToClipboard::oc-camel-k-camelsource-api[]
ifndef::workshop[]
--
endif::[]
====

The command above should list: 

[source,bash,subs="+quotes,+attributes,+macros"]
----
NAME               APIGROUP                       NAMESPACED   KIND
apiserversources   sources.eventing.knative.dev   true         ApiServerSource
camelsources       sources.eventing.knative.dev   true         *CamelSource*
containersources   sources.eventing.knative.dev   true         ContainerSource
cronjobsources     sources.eventing.knative.dev   true         CronJobSource
sinkbindings       sources.eventing.knative.dev   true         SinkBinding
kafkasources       sources.eventing.knative.dev   true         KafkaSource
----

[#logging-ce-messages]
=== View CloudEvents Messages

In order for you to view the events drained from the CamelSource `timed-greeter`, you need to deploy a utility service called `event-display`. Run the following command to deploy the service:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#deploy-ce-event-display]
[source,bash,subs="+quotes,+attributes,+macros"]
----
kubectl apply \
  -f https://github.com/knative/eventing-contrib/releases/download/{knative-version}/event-display.yaml
----
copyToClipboard::deploy-ce-event-display[]
--
oc::
+
--
endif::[]
[#oc-deploy-ce-event-display]
[source,bash,subs="+quotes,+attributes,+macros"]
----
oc apply \
  -f https://github.com/knative/eventing-contrib/releases/download/{knative-version}/event-display.yaml
----
copyToClipboard::oc-deploy-ce-event-display[]
ifndef::workshop[]
--
endif::[]
====

A successful event display should show the following pod in the `{tutorial-namespace}`:

[source,bash,subs="+quotes,+attributes,+macros"]
----
NAME            URL                                                      READY
event-display   http://event-display.{tutorial-namespace}.example.com         True
----

[[camel-k-es-sink]]
=== CamelSource to a Knative Eventing Sink

Knative Eventing semantics allows you to link the Event Source to Event Sink using the **sink** block of the Knative Eventing source specification.

As part of this exercise we will deploy the same `timed-greeter` integration that you deployed <<deploy-camel-k-integration,earlier>> but now as a CamelSource. The event source (CamelSource) is configured to drain the events to the sink `event-display`. 

The following listing provides the details of CamelSource configuration:

.timed-greeter CamelSource
[source,yaml]
----
apiVersion: sources.eventing.knative.dev/v1alpha1 #<1>
kind: CamelSource
metadata:
  name: timed-greeter
spec:
  integration: #<2>
    dependencies:
      - camel:log
  source: #<3>
    flow:
      from:
        uri: "timer:tick"
        parameters:
          period: "10s"
        steps:
          - set-body:
              constant: "Welcome to Apache Camel-K"
          - set-header:
              name: ContentType
              simple: text/plain
          - transform:
              simple: "${body.toUpperCase()}"
          - log:
              message: "${body}"
  sink: #<4>
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display

----
<1> The CamelSource is provided by the API `sources.eventing.knative.dev`, it is now available as a result of deploying the CamelSource event source.
<2> The CamelSource spec has two main sections: `integration` and `source`. The `integration` block is used to configure the Camel-K integration specific properties such as dependencies, traits, etc. In this example we add the required dependencies such as `camel:log`, it is the dependency that you earlier passed via `kamel` CLI.
<3> The `source` block is used to define the Camel-K integration definition. The `flow` attribute of the `source` block allows you define the Camel route.
<4> The event sink for messages from the Camel event source. The sink could be either a Knative Service, Knative Event Channel or Knative Event Broker. In this case it is configured to be the `event-display` Knative Service.

To deploy the CamelSource run the following command:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#deploy-greeter-camelsource]
[source,bash,subs="+quotes,+attributes,+macros"]
----
kubectl apply -n {tutorial-namespace} -f get-started/timed-greeter-source.yaml
----
copyToClipboard::deploy-greeter-camelsource[]
--
oc::
+
--
endif::[]
[#oc-deploy-greeter-camelsource]
[source,bash,subs="+quotes,+attributes,+macros"]
----
oc apply -n {tutorial-namespace} -f get-started/timed-greeter-source.yaml
----
copyToClipboard::oc-deploy-greeter-camelsource[]
ifndef::workshop[]
--
endif::[]
====

A successful deployment will show the CamelSource `timed-greeter` in ready state along with its pods in the {tutorial-namespace} namespace. 

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#camel-k-watch-camelsources]
[source,bash,subs="+quotes,+attributes,+macros"]
----
watch kubectl -n {tutorial-namespace} get camelsources
----
copyToClipboard::camel-k-watch-camelsources[]
--
oc::
+
--
endif::[]
[#oc-camel-k-watch-camelsources]
[source,bash,subs="+quotes,+attributes,+macros"]
----
watch oc -n {tutorial-namespace} get camelsources
----
copyToClipboard::oc-camel-k-watch-camelsources[]
ifndef::workshop[]
--
endif::[]
====

When the camel source is successfully running you will see it in "READY" state `True`:

[source,bash,subs="+quotes,+attributes,+macros"]
----
NAME            READY   AGE
timed-greeter   True    114s
----

You will also see the `event-display` pod scaling up to receive the events from `timed-greeter`.

.CamelSource `timed-greeter` pod and event-display pod
[source,bash,subs="+quotes,+attributes,+macros"]
----
# watch kubectl -n {tutorial-namespace} get pods
NAME                                              READY   STATUS    AGE
camel-k-operator-84d7896b68-sgmpk                 1/1     Running   2m36s
event-display-dmq4s-deployment-775789b565-fnf2t   2/2     Running   17s
timed-greeter-m4chq-7cbf4ddc66-kxpqd              1/1     Running   86s
----

Open a new terminal and run the following command to start watching the events that are being drained into the `event-display` Knative service using the command:

[#camel-k-kn-eventing-logs]
[source,bash,subs="+quotes,+attributes,+macros"]
----
stern -n {tutorial-namespace} event-display -c user-container
----
copyToClipboard::camel-k-kn-eventing-logs[]

The `stern` command above should show the following output:

[source,bash,subs="+quotes,+attributes,+macros"]
----
event-... user-container   id: ID-timed-greeter-m4chq-7cbf4ddc66-kxpqd-1577072133461-0-19
event-... user-container   time: 2019-12-23T03:37:03.432Z
event-... user-container Data,
event-... user-container   WELCOME TO APACHE CAMEL K
event-... user-container ☁️  cloudevents.Event
event-... user-container Validation: valid
event-... user-container Context Attributes,
event-... user-container   specversion: 0.3
event-... user-container   type: org.apache.camel.event
event-... user-container   source: camel-source:knativetutorial/timed-greeter
----

[#cleanup]
=== Cleanup

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#camelk-eventing-cleanup]
[source,bash,subs="+quotes,+attributes,+macros"]
----
kubectl -n {tutorial-namespace} delete camelsource timed-greeter
----
copyToClipboard::camelk-eventing-cleanup[]
--
oc::
+
--
endif::[]
[#oc-camelk-eventing-cleanup]
[source,bash,subs="+quotes,+attributes,+macros"]
----
oc -n {tutorial-namespace} delete camelsource timed-greeter
----
copyToClipboard::oc-camelk-eventing-cleanup[]
ifndef::workshop[]
--
endif::[]
====

After few seconds you will see the `event-display` Knative Service scaling down to zero since it no longer receives events via the event source.
